# Generated by Django 6.0.5 on 2026-05-19 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='created_at',
        ),
        migrations.AddField(
            model_name='exam',
            name='period',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='sections_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='academic_year',
            field=models.CharField(default='1447/1448', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.school'),
        ),
    ]
