# Generated by Django 6.0.5 on 2026-05-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_exam_created_at_exam_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='sheet_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
