# Generated by Django 6.0.5 on 2026-05-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_answersheet_sheet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='sheet_image',
            field=models.ImageField(blank=True, null=True, upload_to='sheets/'),
        ),
    ]
