# Generated by Django 6.0.5 on 2026-05-17 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_answersheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='academic_year',
            field=models.CharField(blank=True, default='1447/1448', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='status',
            field=models.CharField(choices=[('pending', 'لم تُصحح'), ('graded', 'مصححة'), ('error', 'خطأ')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.school'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'student_id')},
        ),
    ]
