# Generated by Django 6.0.5 on 2026-05-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_curriculum_bankquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='semester',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
